### ISSUE TITLE
Linter overload after sorting

### ISSUE THREAD

**Issue by JGH1000** [lexicalunit/atom-isort#13]
First of all, thanks a lot for providing and maintaining the up-to-date package!

I am using Linux with newest Atom and atom-isort and after sorting the imports every line in the script is highlighted as an error by isort. This disappears after saving the file. 

![screenshot from 2017-08-01 10 06 43](https://user-images.githubusercontent.com/27884805/28804900-5cb3655c-76a1-11e7-8a64-232f17c1d1de.png)

Thanks for looking into this.

**Comment by lexicalunit** [comment]
Thank you! And yep I was having that same issue myself today. Saving has the effect of re-running the linter, which fixes things. I tried a few things to get it to work without saving. Triggering a re-lint also works without saving the file, but the underline still appears briefly and then goes away, which is still annoying to me.

I was able to find a way to fix it finally by tweaking the linter integration code a bit. But you're still seeing this happen? 🤔 

@JGH1000, what version of `atom-isort` do you have installed? I had hoped this would be resolved by release v2.2.6.

**Comment by pauloxnet** [comment]
I have this issue too

**Comment by lexicalunit** [comment]
Good data point! I really want to fix this one as soon as possible because it's super annoying.

**Comment by lexicalunit** [comment]
Should be resolved in release v2.3.0 🤞, please re-open this issue if it's not working for you after an upgrade and Atom restart.

**Comment by JGH1000** [comment]
Thanks for a prompt fix!
