### ISSUE TITLE
Atom-isort v2.4.0 not working

### ISSUE THREAD

**Issue by pauloxnet** [lexicalunit/atom-isort#14]
After update to v2.4.0 "sort python imports" menu has no effects on files.

After downgrade to v2.3.0 is starts work again:
```
$ apm uninstall atom-isort
$ apm install atom-isort@2.3.0
```

**Comment by marcelhekking** [comment]
Same for me!

**Comment by lexicalunit** [comment]
Confirmed. `atom.commands.add()` doens't work the way I thought it did. Fixed in v2.5.0.
