### ISSUE TITLE
Only sort python files

### ISSUE THREAD

**Issue by stdavis** [lexicalunit/atom-isort#15]
I love the sort on save! However, it's sorting all file types (.js is the one that's giving me problems). Is there any way to make this package only apply to python files?

**Comment by lexicalunit** [comment]
I'll take a look at this as soon as I can. Thanks for the report!

**Comment by stdavis** [comment]
You're welcome. Thanks for the great package. I'd be happy to help if you want to point me in the right direction.

**Comment by lexicalunit** [comment]
Found the bug! Please give v2.5.1 a shot :)

**Comment by stdavis** [comment]
Works great! No more messing with my `.js` imports but still works with my `.py` ones.

Thanks for the quick response!
