### ISSUE TITLE
Errors on save of Python files

### ISSUE THREAD

**Issue by danpalmer** [lexicalunit/atom-isort#18]
When saving _some_ Python files with `atom-isort` enabled, I get the error message `Error: spawnSync python EPIPE` as an alert in the top-right of the Atom window. The happens regardless of whether "Sort on save" is enabled or disabled.

When saving some other Python files with `atom-isort` enabled, I get the error message:
```
Unexpected errors while running Python process:
Traceback (most recent call last):
  File "/Users/dan/.atom/packages/atom-isort/src/isort-wrapper.py", line 7, in <module>
    import isort
ImportError: No module named isort
```

I have changed the Python path to a virtualenv with isort installed in it (which I have confirmed to be the case), but this did not seem to affect the error messages.

I have tried restarting Atom, but this had no effect.

I have not yet figured out why some files produce the first error and others produce the second.

Atom: 1.23.0-beta1
atom-isort: latest installed through Atom's plugin installation tab.

I'm using Python 3 files with new syntax like f-strings and type attributes, but I'm using an isort that works on those files.

**Comment by lexicalunit** [comment]
So the environment that Atom uses when it starts up is either:

1.  Your default shell environment.
2. The environment of the shell you started Atom from if you started it via the command line.

You might try completely quitting out of Atom and then running `atom` while your virturalenv is activated.

**Comment by danpalmer** [comment]
Thanks for the help.

With other plugins, I typically point them at the Python install of the virtualenv I want to use (ideally with `$PROJECT_NAME` in the path), which then allows the plugin to use any of the resources in that env.

I'm not quite sure why setting the Python path in the settings for `atom-isort` doesn't work?

**Comment by lexicalunit** [comment]
You're right @danpalmer. I took a look at the code for handling the Python path in `atom-isort` and I think there's a bug in there. Fixing now.

**Comment by lexicalunit** [comment]
Please give v2.5.3 a try.

**Comment by danpalmer** [comment]
Amazing, thanks for the fast response! I'll give this a try when I'm back at work tomorrow.

**Comment by danpalmer** [comment]
Just to confirm, this worked, although I had another issue that the isorting being done on save in Atom was subtly different to the isorting being done on the command line directly with isort. I'm not sure why this is, I'll investigate.

**Comment by lantzby** [comment]
Hi Dan,

Does the same solution work with the new Python 3? 
and 
Did you find a solution to the isorting being done on save in Atom was subtly different to the isorting being done on the command line directly with isort?

**Comment by lantzby** [comment]
<img width="727" alt="Screenshot 2019-12-11 16 29 27" src="https://user-images.githubusercontent.com/54217001/70662051-7defd180-1c33-11ea-9560-705e8a3f3a8f.png">
I get this message when I try to save my .py file and I believe that this is the issue why it does not want to run my code completely.

**Comment by danpalmer** [comment]
@lantzby sorry, I actually moved away from Atom shortly after this and haven't used it since.

**Comment by lantzby** [comment]
If you don't mind me asking - What do you use now and why did you change editor?

**Comment by danpalmer** [comment]
I moved back to Sublime Text at the time because it was much faster, but in the end I found it too difficult to get a reliable Python setup for multiple projects that had different Python version requirements and linting/type-checking setups, so I've finally moved to VSCode which I have been on for the past year. We've adopted it more widely in our team as its Python support is very good.

**Comment by lantzby** [comment]
Great info! Thank you Dan, I am doing a full-stack development course using Django and the suggested Atom, it works fine it is just this popup which is annoying...

Anyhow, thanks for your time and info!!

**Comment by lexicalunit** [comment]
I've also moved away from Atom. I went with VSCode instead of Sublime Text. Packages in Atom have too much power and the more you install the slower the editor will run. Due to the way VSCode architected their extensions support this is highly unlikely to happen with VSCode. The last time I used ST was back when it was built on Python 2 and I stopped using it when they were in the process of moving over to Python 3 and all my plugins broke. I tried to write my own plugins for ST3 but found the entire process frustrating and lacking in good documentation, which is why I switched to Atom at that time.

**Comment by lantzby** [comment]
This is great info, thank you @lexicalunit! I will stick with Atom for now until I have finished my e-course because my tutor uses Atom in the course. But when I will start building on my platform I will reconsider.

**Comment by kkhashayar** [comment]
Im having a same problem with Atom, loved it and been using it in a past 2 years. going to try VScode.

**Comment by lantzby** [comment]
@kkhashayar love to see that the thread keeps on being helpful! Good luck with VScode, and I am still using VScode and have not turned back to Atom since the switch.
