### ISSUE TITLE
Keybinding

### ISSUE THREAD

**Issue by tuliocasagrande** [lexicalunit/atom-isort#21]
Greetings,

Thank you for the awesome package.
I'm trying to set up a keybinding for it, but with no success.

So far I tried variations of:
```
'atom-text-editor[data-grammar="source python"]':
  'ctrl-alt-s': 'atom-isort:sortImports'
```

Can you show me the correct syntax?
Thank you!

**Comment by arl-o** [comment]
It's `sort imports`, not `sortImports`. (You can check this by going to the package, clicking 'view code', then looking in `menus/menu.cson`. 

So a version that works for me is:

```
'atom-text-editor[data-grammar="source python"]':
  'ctrl-alt-s': 'atom-isort:sort imports'
```

**Comment by tuliocasagrande** [comment]
thank you, @arl-o!
that worked perfectly.
