### ISSUE TITLE
Incompatible with isort 5

### ISSUE THREAD

**Issue by ezarowny** [lexicalunit/atom-isort#24]
Version 5 of isort has a completely new Python API which breaks atom-isort.

[Line 61 in isort-wrapper.py](https://github.com/lexicalunit/atom-isort/blob/master/src/isort-wrapper.py#L61) is the problem.

**Comment by lexicalunit** [comment]
Oh wow, a new major version of isort! That's neat. Fix in a moment.

**Comment by lexicalunit** [comment]
Ok, give `atom-isort` v3.0.0 a try 👍

**Comment by ezarowny** [comment]
Wow! I appreciate the swiftness of the update here 🙇 

It's also nice to see people still using Atom :atom:
