### ISSUE TITLE
atom isort is not properly disabling

### ISSUE THREAD

**Issue by tardyp** [lexicalunit/atom-isort#7]
If I disable atom isort in the package menu, it does not disable, and continue to run isort.

It is annoying when editing some open source software that does not use isort, and is messing up with their import.

**Comment by lexicalunit** [comment]
Yikes, that seems like a bug with the Atom editor itself. Not sure how I can help, but here's a couple things to try:

1. Completely kill the Atom program and restart it or use the `Window: Reload` command from the Command Palette. Is `atom-isort` still there?
2. When you try to disable the package, can you check the Debug Console to see if there's an error?

**Comment by lexicalunit** [comment]
There was also a bug in older version w/r/t disabling. What version of the package do you have installed?

**Comment by tardyp** [comment]
sorry I forgot to answer this. Is it something you can't reproduce?

**Comment by lexicalunit** [comment]
I can reproduce it on older versions but it should hopefully be resolved in v2.0.0.

**Comment by tardyp** [comment]
I just retested with 2.0.0 and atom 1.18. (fresh install)

I click isort on save. then I save a file -> it sorts the file
I disable atom-isort. I reorder then I save a file -> it sorts the file back
I uncheck isort on save. I reorder then I save a file -> it sorts the file back
I enable atom-isort. I reorder then I save a file -> it sorts the file back
I uncheck isort on save. I reorder then I save a file -> it sorts the file back

**Comment by lexicalunit** [comment]
Confirmed! This is a different kind of disable bug than I was thinking about. Ty for reproduction steps.

**Comment by lexicalunit** [comment]
This should be resolved in v2.1.0.
