### ISSUE TITLE
isort settings not readed

### ISSUE THREAD

**Issue by pauloxnet** [lexicalunit/atom-isort#8]
Atom isort is not reading isort section in project's setup.cfg or tox.ini file as specified in isort docs
https://github.com/timothycrosley/isort#configuring-isort

**Comment by lexicalunit** [comment]
Hrm. All this package does is run:

```
$ isort -ns file.py -vb
```

I'm not sure why it wouldn't pick up those settings if running it manually does pick up those settings. Can you try running the `isort` command manually on your files from the command line and see if that works?

**Comment by lexicalunit** [comment]
The new version 2.0.0 allows more configuration options.

**Comment by pauloxnet** [comment]
Sorry my late answer.

I updated 2.0 version and it allow more configuration, thanks.

But I'm still not able to use different isort settings for different projects, reading it from setup.cfg or tox.ini like wspecified in the isort documentation
https://github.com/timothycrosley/isort#configuring-isort

For example I have a isort configurations in my tox.ini file for personal project and in a setup.cfg when I switch to work on Django core base:
https://github.com/django/django/blob/master/setup.cfg

**Comment by tardyp** [comment]
I am also seing this problem. It used to work with < 2.0. now it does not . 
Trying to find out why...

**Comment by tardyp** [comment]
Looking at the source code, it looks like atom-isort 2.0 does not use the plain isort binary anymore. 

Thus the isort tool cannot find the directory context specific configuration file. For me this is very important that atom-isort use context specific configuration file, as I work on several open source projects which do not have the same policy

**Comment by pauloxnet** [comment]
I found for example an atom package that permit reading setting from file
https://github.com/AtomLinter/linter-flake8#project-configuration-files

**Comment by lexicalunit** [comment]
PR #11 is now in v2.1.0 which should address this issue.

**Comment by sneridagh** [comment]
@lexicalunit Why don't provide a settings option to configure the .isort.cfg file as well?

$ cat ~/.isort.cfg
[settings]
# for details see
# http://docs.plone.org/develop/styleguide/python.html#grouping-and-sorting
force_alphabetical_sort = True
force_single_line = True
lines_after_imports = 2
line_length = 200
not_skip = __init__.py

**Comment by lexicalunit** [comment]
@sneridagh you're totally correct. I've refactored how `atom-isort` calls `isort` internally so that it will pick up settings correctly. With these changes, this package should now be able to pick up settings exactly the same way that `isort` naturally picks up changes. I've removed all the manually settings overrides from the package configuration as well. It would be too much of a hassle to keep up with any changes the `isort` project makes so that my package settings matched the settings they offer.

**Comment by lexicalunit** [comment]
PR #12 will resolved this issue.

**Comment by lexicalunit** [comment]
@sneridagh please give v2.2.0 a try.

**Comment by pauloxnet** [comment]
@lexicalunit thanks for your work

The version 2.2.0 seems have something wrong
```javascript
/home/paulox/.atom/packages/linter/lib/linter-registry.js:159 [Linter] Error running isort SyntaxError: Unexpected token # in JSON at position 0
    at Object.parse (native)
    at AtomIsort.module.exports.AtomIsort.isortRequest (/home/paulox/.atom/packages/atom-isort/lib/atom-isort.coffee:80:31)
    at AtomIsort.module.exports.AtomIsort.checkImports (/home/paulox/.atom/packages/atom-isort/lib/atom-isort.coffee:11:6)
    at AtomIsortLinter.module.exports.AtomIsortLinter.lint (/home/paulox/.atom/packages/atom-isort/lib/atom-isort-linter.coffee:13:18)
    at promises.push.Promise.then._this2.emitter.emit.number (/home/paulox/.atom/packages/linter/lib/linter-registry.js:101:24)
    at _loop (/home/paulox/.atom/packages/linter/lib/linter-registry.js:99:21)
    at LinterRegistry.<anonymous> (/home/paulox/.atom/packages/linter/lib/linter-registry.js:87:40)
    at next (<anonymous>)
    at LinterRegistry.<anonymous> (/home/paulox/.atom/packages/linter/lib/linter-registry.js:143:4)
    at next (<anonymous>)
    at step (/home/paulox/.atom/packages/linter/lib/linter-registry.js:5:273)
    at /home/paulox/.atom/packages/linter/lib/linter-registry.js:5:443
    at LinterRegistry.<anonymous> (/home/paulox/.atom/packages/linter/lib/linter-registry.js:5:99)
    at /home/paulox/.atom/packages/linter/lib/main.js:125:30
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at EditorLinter.lint (/home/paulox/.atom/packages/linter/lib/editor-linter.js:40:18)
    at EditorRegistry.createFromTextEditor (/home/paulox/.atom/packages/linter/lib/editor-registry.js:43:20)
    at /home/paulox/.atom/packages/linter/lib/editor-registry.js:25:12
    at Workspace.observeTextEditors (/usr/share/atom/resources/app/src/workspace.js:717:15)
    at EditorRegistry.activate (/home/paulox/.atom/packages/linter/lib/editor-registry.js:24:43)
    at Linter.registryEditorsInit (/home/paulox/.atom/packages/linter/lib/main.js:132:26)
    at Linter.registryEditorsIdleInit (/home/paulox/.atom/packages/linter/lib/main.js:103:14)(anonymous function)
```

**Comment by lexicalunit** [comment]
Can you post the python source code that is causing the error?

**Comment by pauloxnet** [comment]
@lexicalunit the error appened for every non empty python file, also a file with only `import os`

I already tried to close (kill) Atom and open it again.

My Atom version i s 1.18.0

**Comment by sneridagh** [comment]
@lexicalunit Same error here when executing the sorting and when I open a new Python file.

**Comment by lexicalunit** [comment]
@pauloxnet and @sneridagh: What operating systems are you on? I'm on macOS. Maybe the problem is OS specific?

**Comment by sneridagh** [comment]
@lexicalunit MacOS

**Comment by pauloxnet** [comment]
I'm on Ubuntu Gnu/Linux

**Comment by lexicalunit** [comment]
Welp. I guess OS isn't related. Thanks for the quick responses. 🤔

**Comment by lexicalunit** [comment]
I think I found the issue where it causes an error when opening a new (empty) *.py file. I also added a lot more exception handling and error notifications to hopefully try and help zero on the error. I'm still not able to reproduce it on my side :(

Released as v2.2.1.

**Comment by pauloxnet** [comment]
I updated to v2.2.1 and after a restart a tried to open a simple python file with this error

**Could not parse isort response**
```python
from __future__ import absolute_import
{"type": "check_text_response", "correctly_sorted": true}
```

**Comment by sneridagh** [comment]
@lexicalunit Now the error is: Could not parse isort response. (the content of the file is displayed in the error).

**Comment by lexicalunit** [comment]
Interesting. So it seems like the redirect to `/dev/null` is not working:

```
        with silence_stdout():
            new_contents = isort.SortImports(file_contents=request['file_contents'],
                                             file_path=request['file_path'],
                                             write_to_stdout=True).output
```

Where:

```
@contextmanager
def silence_stdout():
    new_target = open(os.devnull, 'w')
    old_target, sys.stdout = sys.stdout, new_target
    try:
        yield new_target
    finally:
        sys.stdout = old_target
```

When isort runs, I have `write_to_stdout=True` to prevent isort from writing to the file in-place. This enables a user to unselect `Sort On Save` in the config settings and have that actually work.

We want to simply ignore that output and write our own output instead which `atom-isort` can then interpret correctly. So I tell isort to write to STDOUT, but then I redirect STDOUT to nothing for just that function call. This seems to work on my machine, and it was the reason I was speculating that maybe machine OS had something to do with it. I was thinking maybe there was a portability issue with respect to STDOUT redirection or something along those lines.

**Comment by lexicalunit** [comment]
@pauloxnet @sneridagh can you verify the following:

```shell
$ cat ~/.atom/packages/atom-isort/lib/atom-isort.py | grep silence_stdout
def silence_stdout():
        with silence_stdout():
```

That should let you know if you've got the correct version of the python interface file. The one with `silence_stdout()` in it.

**Comment by sneridagh** [comment]
Yep.
```$ cat ~/.atom/packages/atom-isort/lib/atom-isort.py | grep silence_stdout
def silence_stdout():
        with silence_stdout():```

**Comment by lexicalunit** [comment]
Oh! Also can you run this command and post the output? I think maybe I know what could be the issue❗️ 

```shell
$ ls ~/.atom/packages/atom-isort/lib
```

**Comment by sneridagh** [comment]
```
$ ls ~/.atom/packages/atom-isort/lib
atom-isort-linter.coffee atom-isort.coffee        atom-isort.py            index.coffee
```

**Comment by lexicalunit** [comment]
Damn. I was thinking maybe there was a stale `.pyo` or `.pyc` file in there that was interfering with the package updates. But no, that looks like it's not the issue either. I'm not sure what's going on here that stdout redirection works for me but doesn't work for both of you. :(

**Comment by lexicalunit** [comment]
So frustrating. Sorry for troubling you both @pauloxnet; @sneridagh. I think I have a solution. It's hard for me to test though because I'm unable to reproduce the errors you're seeing on my machine. I'm still using the stdout silencer, but I have also implemented a quick workaround in the code in case it fails. It should still be pretty fast, but if it causes any performance issues please let me know! Fix is released in v2.2.5.

**Comment by pauloxnet** [comment]
hi @lexicalunit after upgrade it doesn't show warning for every python file :+1: 

Unfortunately it seems not use isort setting from `[isort]` section in my `tox.ini` as command line do
https://github.com/timothycrosley/isort#configuring-isort

**Comment by sneridagh** [comment]
@lexicalunit It seems it worked for me! Also seems to be applying .isort.cfg file, so all solved at my end! Thanks for the effort!

**Comment by lexicalunit** [comment]
It looks like [reading `tox.ini` was added to `isort` on Jan. 7th of this year](https://github.com/timothycrosley/isort/commit/3d61a57cbac1c22b2d634db08ee35a47941c26f2). The next release after this delta looks like **4.2.8**. @pauloxnet, can you ensure that the version of `isort` you have installed is this version or newer?

```shell
$ python -c "import isort; print(isort.__version__)"
4.2.15
```

Meanwhile I'm going to try and recreate the issue on my machine. I was able to get it to pick up settings in `.isort.cfg` files in projects, as well as `~/.isort.cfg`. But I didn't test to see if it would pick up settings in `setup.cfg`, `tox.ini`, or `.editorconfig' files. I just assumed that if `.isort.cfg` files worked, that the others would too. 😞

**Comment by pauloxnet** [comment]
I use different virtualenv for my different projects with different python version

@lexicalunit how can I check which version of isort is used by atom ?

**Comment by lexicalunit** [comment]
@pauloxnet if you start Atom from the command line using `atom` then it will pick up whatever env you have active in that shell at that time. If you start atom using a launcher then Atom has some code that attempts to load your default environment by quickly spinning up a shell and fetching whatever environment it finds when it does that.

**Comment by sneridagh** [comment]
@pauloxnet I have isort installed in System's default python... not a big deal.

**Comment by lexicalunit** [comment]
Yeah, I did the same a while back just to ensure that it's _always_ there no matter what. I have to remember to update it every now and then though if I want the latest and greatest.

**Comment by pauloxnet** [comment]
@sneridagh I already have isort installed in system's default python, but unfortunately  is 4.2.5 and it can't read configration from tox.in

@lexicalunit I had upgraded system isort version to 4.2.15 and now it works :+1:

**Comment by Lordnibbler** [comment]
Has anyone tried using the `skip_glob` setting? this plugin seems to not enjoy it:

```
Traceback (most recent call last):
  File "/Users/nibbler/.atom/packages/atom-isort/src/isort-wrapper.py", line 114, in <module>
    IsortTools().read_and_process()
  File "/Users/nibbler/.atom/packages/atom-isort/src/isort-wrapper.py", line 110, in read_and_process
    self._process_request(data)
  File "/Users/nibbler/.atom/packages/atom-isort/src/isort-wrapper.py", line 64, in _process_request
    write_to_stdout=True).output
AttributeError: 'SortImports' object has no attribute 'output'
```
